#ifndef PUBLIC_KEY_H
#define PUBLIC_KEY_H

const char rsa_public_key_pem[] =
"-----BEGIN PUBLIC KEY-----\n"
"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvIUxo9uCki9u1wJykMhR\n"
"J91Qtc8AkDbchE2B0x1SatUShM41XD4TiKJYklgw8U4MEczVzKR8CzmdKY/AHUd6\n"
"OIA1oenaqQmOCG8Yiv1qYovgFXl4He92awCN60TfXWP9txTGTwQfKXLKutyuIn99\n"
"4qT4et6QarnYjZ8OviXhbwatLGLivLZrUrUk4NQfdalHCK65RGxTRWaMcARVJIGu\n"
"HLMVtM0/4goAOEz/KT1u28QBVYwzX9lPWuu4jRHZE8z5cHeiwgIn0swZBc4d5h/Z\n"
"HvcloHROfDVkEZAB0jWfcW58aq9fGWvDwk0TXNyU1bS/2FkxT0CJzoTgs2dKMJpC\n"
"WwIDAQAB\n"
"-----END PUBLIC KEY-----\n";

#endif // PUBLIC_KEY_H
